
  spring:
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
    datasource:
      url: jdbc:mysql://localhost:3306/community-mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    mail:
      host: smtp.gmail.com
      port: 587
      username: kyy970207@gmail.com
      password: jnvfxojphfjtnahj
      properties:
        mail:
          smtp:
            starttls:
              enable: true
            ssl:
              trust: smtp.gmail.com
  jwt:
    # ?? ???? ?? ???? ?? ??
    secret: ZGF5b25lLXNwcmluZy1ib290LWRpdmlkZW5kLXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXk=